project_id = "tyakwdphlcbteyuhsftl"

[functions.analyze-sentiment]
verify_jwt = false

[functions.reanalyze-thoughts]
verify_jwt = false

[functions.setup-admin]
verify_jwt = false

[functions.generate-weekend-suggestions]
verify_jwt = false

[functions.cleanup-users]
verify_jwt = false
